b4: loosen versions for request and dnspython
Until the next stable release, we need to loosen the version
requirements ourselves by hand for dnspython, since NixOS has updated to
version 2.1. While at it, adjust requests from ~=2.24.0 to ~=2.25 which
effectively enables all 2.* versions for requests.

Fixes the following build error:

  adding 'b4-0.6.2.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /build/b4-0.6.2/dist /build/b4-0.6.2
  Processing ./b4-0.6.2-py3-none-any.whl
  Requirement already satisfied: dkimpy~=1.0.5 in /nix/store/3war2scyn6pnrhhcfdx48vd5023x2rkp-python3.8-dkimpy-1.0.5/lib/python3.8/site-packages (from b4==0.6.2) (1.0.5)
  ERROR: Could not find a version that satisfies the requirement dnspython~=2.0.0 (from b4)
  ERROR: No matching distribution found for dnspython~=2.0.0